function Lh = compute_Lh(itrn, itst, x, h)
% Lh = compute_Lh(itrn, itst, x, h)
%
%   Computes the average log-likelihood over training/test splits generated
%   by crossval for a fixed kernel bandwidth h.
%
%   Parameters:
%       itrn, itst - data splits (indices) generated by crossval()
%       x - the data itself
%       h - kernel bandwidth
%
%   Returns:
%       Lh - average log-likelihood over training/test splits

Lh = 0;

for i = 1:size(itrn,2)
    L = my_parzen(x(cell2mat(itst(i))), x(cell2mat(itrn(i))), h);
    Lh = Lh + sum(log(L),2);
end

Lh = Lh / size(itrn,2);
